name: Deploy to minikube

on:
  push:
    branches:
      - features

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: | 
          docker build -t afangndong/name-age-app:latest .
          docker push afangndong/name-age-app:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set KUBECONFIG
        run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        
      - name: Apply Kubernetes manifests
        run: |
          export KUBECONFIG=./kubeconfig.yaml
          kubectl apply -f k8s/features/namespace.yaml  --validate=false


      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s/features/namespace.yaml
          kubectl apply -f k8s/features/deployment.yaml
          kubectl apply -f k8s/features/services.yaml
